### ISSUE TITLE
user-can-see-their-car

### ISSUE THREAD

**Issue by josephswpark** [josephhparkk/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Add` div` for the whole page to change the color
- [x] Make the car visible first on top 
- [x] Ensure that CSS is set for the page
