### ISSUE TITLE
user-can-turn-their-car

### ISSUE THREAD

**Issue by josephswpark** [josephhparkk/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [ ] Create a data model that includes which way the car is facing
- [ ] listen for 'keydown' on the car to change direction depending on what key was pressed
- [ ] test all functionality again 
- [ ] fix all errors
